"""Add new_feature_table

Revision ID: 5ee163824802
Revises: 5fffd0a21a7f
Create Date: 2025-08-02 18:25:17.988681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models import GUID



# revision identifiers, used by Alembic.
revision: str = '5ee163824802'
down_revision: Union[str, None] = '5fffd0a21a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_performance',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('total_failures', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_snippets',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_code_snippets_language', 'code_snippets', ['language'], unique=False)
    op.create_index('idx_code_snippets_user_id', 'code_snippets', ['user_id'], unique=False)
    op.create_index(op.f('ix_code_snippets_user_id'), 'code_snippets', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('preferred_theme', sa.String(length=20), nullable=True),
    sa.Column('auto_save', sa.Boolean(), nullable=True),
    sa.Column('show_line_numbers', sa.Boolean(), nullable=True),
    sa.Column('enable_autocomplete', sa.Boolean(), nullable=True),
    sa.Column('enable_syntax_highlighting', sa.Boolean(), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('tab_size', sa.Integer(), nullable=True),
    sa.Column('preferences_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('api_usage', sa.Column('language', sa.String(length=50), nullable=True))
    op.create_index('idx_api_usage_created_at', 'api_usage', ['created_at'], unique=False)
    op.create_index('idx_api_usage_session_id', 'api_usage', ['session_id'], unique=False)
    op.create_index('idx_api_usage_user_id', 'api_usage', ['user_id'], unique=False)
    op.create_index('idx_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index('idx_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('idx_chat_sessions_created_at', 'chat_sessions', ['created_at'], unique=False)
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('idx_code_analyses_session_id', 'code_analyses', ['session_id'], unique=False)
    op.create_index('idx_code_executions_created_at', 'code_executions', ['created_at'], unique=False)
    op.create_index('idx_code_executions_session_id', 'code_executions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_code_executions_session_id', table_name='code_executions')
    op.drop_index('idx_code_executions_created_at', table_name='code_executions')
    op.drop_index('idx_code_analyses_session_id', table_name='code_analyses')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_created_at', table_name='chat_sessions')
    op.drop_index('idx_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_created_at', table_name='chat_messages')
    op.drop_index('idx_api_usage_user_id', table_name='api_usage')
    op.drop_index('idx_api_usage_session_id', table_name='api_usage')
    op.drop_index('idx_api_usage_created_at', table_name='api_usage')
    op.drop_column('api_usage', 'language')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_code_snippets_user_id'), table_name='code_snippets')
    op.drop_index('idx_code_snippets_user_id', table_name='code_snippets')
    op.drop_index('idx_code_snippets_language', table_name='code_snippets')
    op.drop_table('code_snippets')
    op.drop_table('model_performance')
    # ### end Alembic commands ###
