"""Make session_id nullable in api_usage

Revision ID: 5fffd0a21a7f
Revises: e81bf0caf3fe
Create Date: 2025-08-01 20:41:39.262116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fffd0a21a7f'
down_revision: Union[str, None] = 'e81bf0caf3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
